const API_BASE_URL = 'http://localhost:5000/api';

const ENDPOINTS = {
  ME: `${API_BASE_URL}/me`,
  LOGIN: `${API_BASE_URL}/login`,
  REGISTER: `${API_BASE_URL}/register`,
  LOGOUT: `${API_BASE_URL}/logout`,
  REFRESH: `${API_BASE_URL}/refresh`,
  APPLICATION: `${API_BASE_URL}/application`,
  GET_RECORDS: `${API_BASE_URL}/getRecords`,
  UPDATE_RECORD: `${API_BASE_URL}/updateRecord`,
  MY_JOB_IDS: `${API_BASE_URL}/myJobIds`,
  MY_JOB_IDS_BY_STATUS: `${API_BASE_URL}/myJobIdsByStatus`,
  JOBS_SEARCH: `${API_BASE_URL}/jobs/search`,
  AGENT_GENERATE_COVER_LETTER: `${API_BASE_URL}/agent/cover-letter`,
  AGENT_GET_COVER_LETTERS: `${API_BASE_URL}/agent/cover-letters`,
  AGENT_GET_ALL_COVER_LETTERS: `${API_BASE_URL}/agent/cover-letters`,
  AGENT_GENERATE_COLD_EMAIL: `${API_BASE_URL}/agent/cold-email`,
  AGENT_MATCH_JOBS: `${API_BASE_URL}/agent/match-jobs`,
  AGENT_INTERVIEW_PREP: `${API_BASE_URL}/agent/interview-prep`,
  AGENT_INSIGHTS: `${API_BASE_URL}/agent/insights`,
  AGENT_MARKET_TRENDS: `${API_BASE_URL}/agent/market-trends`,
  AGENT_FOLLOW_UPS: `${API_BASE_URL}/agent/follow-ups`,
  AGENT_STALE_APPLICATIONS: `${API_BASE_URL}/agent/stale-applications`,
  AGENT_GENERATE_FOLLOW_UPS: `${API_BASE_URL}/agent/follow-ups/generate`,
  PREFERENCES_INITIALIZE: `${API_BASE_URL}/agent/preferences/initialize`,
  PREFERENCES: `${API_BASE_URL}/agent/preferences`,
  AGENT_ALERTS: `${API_BASE_URL}/agent/alerts`,
  AGENT_ALERTS_CHECK: `${API_BASE_URL}/agent/alerts/check`,
  AGENT_ALERTS_UNREAD: `${API_BASE_URL}/agent/alerts/unread`,
  AGENT_RESUME_UPLOAD: `${API_BASE_URL}/agent/resume/upload`,
  AGENT_RESUMES: `${API_BASE_URL}/agent/resumes`,
  AGENT_RESUME_ANALYZE: `${API_BASE_URL}/agent/resume/analyze`,
  AGENT_RESUME_TAILOR: `${API_BASE_URL}/agent/resume/tailor`,
  AGENT_AUTO_APPLY_CONFIG_INITIALIZE: `${API_BASE_URL}/agent/auto-apply/config/initialize`,
  AGENT_AUTO_APPLY_CONFIG: `${API_BASE_URL}/agent/auto-apply/config`,
  AGENT_AUTO_APPLY_CHECK: `${API_BASE_URL}/agent/auto-apply/check`,
  AGENT_AUTO_APPLY_QUEUE: `${API_BASE_URL}/agent/auto-apply/queue`,
  AGENT_AUTO_APPLY_STATS: `${API_BASE_URL}/agent/auto-apply/stats`,
};

export { API_BASE_URL, ENDPOINTS };
